/*
 * Copyright (C) 2013 Invenzzia Group <http://www.invenzzia.org/>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package org.invenzzia.opentrans.lightweight.ui.tabs.world.popups;

import org.invenzzia.opentrans.visitons.data.Platform.PlatformRecord;

/**
 * Simple dialog for changing the name of the platform.
 * 
 * @author Tomasz Jędrzejewski
 */
public class PlatformRenameDialog extends javax.swing.JDialog {
	/**
	 * The platform name to return.
	 */
	private String platformName;
	/**
	 * Whether the choice has been confirmed?
	 */
	private boolean confirmed = false;

	/**
	 * Creates new form PlatformRenameDialog
	 */
	public PlatformRenameDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		this.initComponents();
	}
	
	/**
	 * Installs a model.
	 * 
	 * @param platformRecord 
	 */
	public void setModel(PlatformRecord platformRecord) {
		this.platformName = platformRecord.getName();
		this.platformNameField.setText(platformRecord.getName());
		this.setTitle("Rename platform for: "+platformRecord.getStop().getName());
	}
	
	/**
	 * Returns the set platform name.
	 * 
	 * @return 
	 */
	public String getPlatformName() {
		return this.platformName;
	}
	
	/**
	 * Returns true, if the action has been confirmed.
	 * 
	 * @return 
	 */
	public boolean isConfirmed() {
		return this.confirmed;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
	 * method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        platformNameLabel = new javax.swing.JLabel();
        platformNameField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        platformNameLabel.setText("New platform name:");

        platformNameField.setText("Platform name");
        platformNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platformNameFieldActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(platformNameLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(platformNameField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 128, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(platformNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(platformNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
		this.platformName = this.platformNameField.getText();
		this.confirmed = true;
		this.setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		this.confirmed = false;
		this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void platformNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platformNameFieldActionPerformed
		this.platformName = this.platformNameField.getText();
		this.confirmed = true;
		this.setVisible(false);
    }//GEN-LAST:event_platformNameFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField platformNameField;
    private javax.swing.JLabel platformNameLabel;
    // End of variables declaration//GEN-END:variables
}
